name: Bump Provider and Module Versions and Publish

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  bump-versions:
    uses: Evi1Pumpkin/registry/.github/workflows/bump-versions.yml@main
    with:
      environment: "Production"

  publish-versions:
    needs: bump-versions
    uses: Evi1Pumpkin/registry/.github/workflows/generate-and-deploy.yml@main
    with:
      environment: "Production"
